Icap new module
waarp/Waarp-All pull request #48
Opened 2020-06-22 15:17 UTC by fredericBregier

The ICAP Task Type allow to launch a ICAP scan file command with the following options:

- -file filename
- -to hostname
- [-port port, default 1344]
- -service name | -model name
- [-previewSize size, default none]
- [-blocSize size, default 8192]
- [-receiveSize size, default 65536]
- [-maxSize size, default MAX_INTEGER]
- [-timeout in_ms, default equiv to 10 min]
- [-keyPreview key -stringPreview string, default none]
- [-key204 key -string204 string, default none]
- [-key200 key -string200 string, default none]
- [-stringHttp string, default none]
- [-logger DEBUG|INFO|WARN|ERROR, default none]
- [-errorMove path | -errorDelete | -sendOnError]
- [-ignoreNetworkError]

Then if r66send command in case of -sendOnError option is specified, the
very last option of ICAP must be "--" then followed by usual r66send
options.

Format is like r66send command in any order except "-info" which should be
the last item, and "-copyinfo" will copy at first place the original transfer information as the new one,
while still having the possibility to add new informations through "-info":

      "-file filepath -to requestedHost -rule rule [-md5] [-start yyyyMMddHHmmss or
       -delay (delay or +delay)]
       [-copyinfo] [-info information]"

INFO is the only one field that can contains blank character.

Example:

      -file #TRUEFULLPATH# -to hostname -service name -previewSize size
      -blocSize size -receiveSize size -maxSize size -timeout in_ms -keyPreview
       key -stringPreview string -key204 key -string204 string -key200 key
      -string200 string -stringHttp string -logger WARN -errorDelete
      -ignoreNetworkError

      -file #TRUEFULLPATH# -to hostname -model name -previewSize size
      -blocSize size -receiveSize size -maxSize size -timeout in_ms -keyPreview
      key -stringPreview string -key204 key -string204 string -key200 key
      -string200 string -stringHttp string -logger WARN -errorMove path
      -ignoreNetworkError

      -file #TRUEFULLPATH# -to hostname -model name -previewSize size
      -blocSize size -receiveSize size -maxSize size -timeout in_ms -keyPreview
      key -stringPreview string -key204 key -string204 string -key200 key
      -string200 string -stringHttp string -logger WARN -sendOnError
      -ignoreNetworkError -- -file #TRUEFULLPATH# -to
      requestedHost -rule rule [-copyinfo] [-info information]

Also fix issue on Task arguments with duplicate whitespaces or newline

First part for ICAP support for Antivirus: command line

The command line is as follow:

IcapScanFile

- -file <arg>              Specify the file path to operate on (f arg is EICARTEST, will send a fake virus
                             based on EICAR test)
- -to <arg>                Specify the requested Host
- [-port <arg>]            Specify the port on remote host to use
- -service <arg> |         Specify the service on remote host to use
- -model arg               Specify the model of service on remote host to use

- [-maxSize <arg>]         Specify the Max file size to use
- [-previewSize <arg>]     Specify the Preview size to use
- [-blocSize <arg>]        Specify the Block size to use
- [-receiveSize <arg>]     Specify the Receive size to use
- [-timeout in_ms]         Specify the timeout in ms

- [-keyPreview <arg>]      Specify the key for Options to validate
- [-stringPreview <arg>]   Specify the substring for key for Options to
                           validate
- [-key204 <arg>]          Specify the key for 204 ICAP to validate
- [-string204 <arg>]       Specify the substring for key for 204 ICAP to
                           validate
- [-key200 <arg>]          Specify the key for 200 ICAP to validate
- [-string200 <arg>]       Specify the substring for key for 200 ICAP to
                           validate
- [-stringHttp <arg>]      Specify the substring for HTTP 200 ICAP status to
                           validate

- [-errorDelete |          Specify the error delete action if wrong scan
- -errorMove <arg>|        Specify the path to use if wrong scan
- -sendOnError]            Specify the wrong file will be send somewhere else

- [-ignoreNetworkError]    Specify that a network error will gives a result of OK

- [-logger <arg>]          Specify the level of log between DEBUG | INFO |
                           WARN | ERROR

It returns exit value as follow:
- 0: File is OK
- 1: Bad arguments
- 2: ICAP protocol error
- 3: Network error
- 4: File is KO
- 5: File is KO but bad access to file during post error action

2020-06-24 16:06 UTC, bcarlin requested changes
Ok, That's a lot of comments, but a huge part are just typos in the documentation...

there is just on thing: ICAP task and command have a `-blocSize` where it should be `-blockSize`...

Fine by me!

2020-06-24 16:06 UTC, bcarlin commented on WaarpIcap/lgpl-3.0.txt
> +		   GNU LESSER GENERAL PUBLIC LICENSE
Why this file (the LGPLv3 license text), since the `LICENSE.txt` file is GPLv3 ?

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +Ceci enverra un trap SNMP/info cotenant ``information`` et le TransferID.
typo 

```suggestion
Ceci enverra un trap SNMP/info contenant ``information`` et le TransferID.
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +obtenu sera un chemin abcolu (et non un chemin relatif).
typo

```suggestion
obtenu sera un chemin absolu (et non un chemin relatif).
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +obtenu sera un chemin abcolu (et non un chemin relatif).
typo

```suggestion
obtenu sera un chemin absolu (et non un chemin relatif).
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +Le fichier sera un lien vers le répertoire ``/newpath/`` avec pour nom ``filenamelink`` (ou une copie si ce
just a clarification

```suggestion
Le fichier sera un lien dans le répertoire ``/newpath/`` avec pour nom ``filenamelink`` (ou une copie si ce
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +obtenu sera un chemin abcolu (et non un chemin relatif).
typo
```suggestion
obtenu sera un chemin absolu (et non un chemin relatif).
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +- Aucun autre arguments n'est pris en compte.
typo
```suggestion
- Aucun autre argument n'est pris en compte.
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +Le fichier effacera le fichier courant. En conséquences, plus aucune action ne peut être opérée sur le
typo
```suggestion
Le fichier courant est effacé. En conséquence, plus aucune action ne peut être opérée sur le
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +Crée un TAR depuis les arguments comme source et destination ou un UNTAR des fichiers depuis un TAR file.
rewording to clarify
```suggestion
Crée un TAR depuis les arguments comme source et destination ou un UNTAR des fichiers depuis une archive TAR.
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +
rewording
```suggestion
- Si ``delay`` est ``1``, l'archive tar indiquée en premier argument est
  **extrait** dans le dossier indiqué en second argument (le ``path``
  ``archiveFile destDir`` équivaut à la commande
  ``tar xf archiveFile -C destDir``)
- Si ``delay`` est ``2``, l'archive tar indiquée en premier argument est
  **crée** avec le contenu du dossier indiqué en second argument (le ``path``
  ``archiveFile sourceDir`` équivaut à la commande
  ``tar cf archiveFile sourceDir``)
- Si ``delay`` est ``3``, l'archive tar indiquée en premier argument est
  **crée** avec les fichiers indiqués dans les arguments suivants (le 
  ``path`` ``archiveFile sourceFile1 sourceFile2`` équivaut à la commande
  ``tar cf archiveFile sourceFile1 sourceFile2``)
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +
rewording
```suggestion
- Si ``delay`` est ``1``, l'archive zip indiquée en premier argument est
  **extraite** dans le dossier indiqué en second argument (le ``path``
  ``archiveFile destDir`` équivaut à la commande
  ``unzip archiveFile -d destDir``)
- Si ``delay`` est ``2``, l'archive zip indiquée en premier argument est
  **crée** avec le contenu du dossier indiqué en second argument (le ``path``
  ``archiveFile sourceDir`` équivaut à la commande
  ``zip -r archiveFile sourceDir``)
- Si ``delay`` est ``3``, l'archive zip indiquée en premier argument est
  **crée** avec les fichiers indiqués dans les arguments suivants (le 
  ``path`` ``archiveFile sourceFile1 sourceFile2`` équivaut à la commande
  ``zip archiveFile sourceFile1 sourceFile2``)
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +- Greece: x-IBM875 or x-IBM1124
First link is dead. The second still work though...
```suggestion
Codages supportés
'''''''''''''''''

Parmi les ensembles de codages, les plus connus sont :

- France: IBM297 or IBM01147
- Italy: IBM280 or IBM01144
- UK: IBM285 or IBM01146
- International (Switzerland, Belgium): IBM500 or IBM01148
- Austria/Germany: IBM273 or IBM01141
- Spain and Latin America: IBM284 or IBM01145
- Portugal, Brazil, USA, Canada, Netherlands: IBM037 or IBM01140
- Central and Eastern Europe: IBM870
- Cyrillic: x-IBM1025 (x-IBM1381?)
- Turkey: IBM1026
- Cyrillic Ukraine: x-IBM1123
- Denmark, Norway: IBM277 or IBM01142
- Finland or Sweden: IBM278 or IBM01143
- Greece: x-IBM875 or x-IBM1124

.. seealso::

    * `référence IBM des code pages <http://publib.boulder.ibm.com/infocenter/pcomhelp/v5r9/topic/com.ibm.pcomm.doc/reference/html/hcp_reference.htm>`__

```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +    [-csv | -html | -text ]
This command does not exist anymore.
The command mentioned above works though

```suggestion
Une méthode en ligne de commande (depuis Waarp Common) permet d'obtenir une liste en html (``-html``), csv
(``-csv``) ou au format texte (``-text``) de tous les codages supportés par votre JVM. Pour l'utiliser,
exécuter la commande suivante :

.. code-block::

  java -cp WaarpCommon-1.2.7.jar \
    org.waarp.common.transcode.CharsetsUtil \
    [-csv | -html | -text ]

Elle peut également être utilisé pour transcoder des fichiers en dehors de R66.

.. code-block::

  java -cp WaarpCommon-1.2.7.jar \
    org.waarp.common.transcode.CharsetsUtil \
    -from fromFilename fromCharset -to toFilename toCharset
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +
Moved below
```suggestion
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +- Si ``Delay`` est 2 = produiera un log de niveau warn
typo
```suggestion
- Si ``delay`` est 1, la tâche produira un log de niveau info
- Si ``delay`` est 2, la tâche produira un log de niveau warn
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +INFO en cas de non erreur, de niveau ERROR en cas d'erreur.
rewording
```suggestion
INFO en l'absence d'erreur, de niveau ERROR en cas d'erreur.
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +
formatting and rewording
```suggestion
- ``SIZE LT/GT/LTE/GTE/EQ number``

  - vérifie la taille du fichier en fonction d'une limite (plus petit, plus grand, plus petit ou égal, plus
    grand ou égal, égal)

- ``DFCHECK``

  - vérifie que la taille du fichier à recevoir est compatible avec l'espace disponible restant tant sur
    l'espace de travail que sur l'espace final de réception (depuis le contexte)

```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +``a+w`` ``a-r`` donnera ``a=w``.
formatting
```suggestion
Si plusieurs modes sont indiqués, ils seront exécutés en séquence.  Ainsi ``a=r a+w a-r`` donnera ``a=w``.
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +- toute autre valeurs pour une exécution en erreur
typo
```suggestion
- exit 1, pour une exécution correcte mais avec avertissement
- toute autre valeur pour une exécution en erreur
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +- toute autre valeurs pour une exécution en erreur
typo
```suggestion
- exit 1, pour une exécution correcte mais avec avertissement
- toute autre valeur pour une exécution en erreur
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +- toute autre valeurs pour une exécution en erreur et seulement dans ce cas, la sortie standard est
typo
```suggestion
- exit 1, pour une exécution correcte mais avec avertissement
- toute autre valeur pour une exécution en erreur et seulement dans ce cas, la sortie standard est
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +  est obtenu comme le premier argument. L'allocation est réalise sous la forme ``new MyClass()``,
typo
```suggestion
  est obtenu comme le premier argument. L'allocation est réalisée sous la forme ``new MyClass()``,
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +- Enfin, il y a la possibilité d'associer une classe `Business (voir ``R66BusinessInterface``) au travers
typos
```suggestion
Afin de faciliter l'intégration dans des modules applicatifs, Waarp R66
supporte la possibilité de déclencher des classes Java spécifiques de 3
manières (depuis la version 2.3) :

- L'une est au travers de tâches de traitement pré- ou post-transfert, ou en
  cas d'erreur  en utilisant le mot clef EXECJAVA, suivi du nom complet de la
  classe Java qui doit implémenter l'interface ``R66Runnable``.
- Une autre est d'exécuter des commandes spécifiques ``R66Business``, qui sont
  également des implémentations de l'interface ``R66Runnable`` au travers de
  l'extension de ``AbstractExecJavaTask``.
- Enfin, il y a la possibilité d'associer une classe ``Business`` (voir
  ``R66BusinessInterface``) au travers
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +Replanifie une tâche de transfert en cas d'erreur avec un délai spécifie en millisecondes, si le code
typo
```suggestion
Replanifie une tâche de transfert en cas d'erreur avec un délai spécifié en millisecondes, si le code
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +indispensables) :
rewording
```suggestion
La balise ``path`` accepte les arguments suivants (les deux premiers sont
obligatoires) :
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +  - Si aucune n'est spécifiée, la date planifiée sera toujours valide.
Rewording and typos
```suggestion
- ``-delay ms`` spécifie le délai en millisecondes après lequel retenter ce
  transfert
- ``-case errorCode,errorCode,...`` où les "errorCode" sont une liste de codes
  d'erreur pour lesquels la tâche est exécutée. Les codes suivants sont
  disponibles (e nom de l'erreur et le code d'une lettre peuvent petre
  utilisés) :

  - ``ConnectionImpossible(C)``,
  - ``ServerOverloaded(l)``
  - ``BadAuthent(A)``,
  - ``ExternalOp(E)``
  - ``TransferError(T)``
  - ``MD5Error(M)``
  - ``Disconnection(D)``
  - ``RemoteShutdown(r)``
  - ``FinalOp(F)``
  - ``Unimplemented(U)``
  - ``Shutdown(S)``
  - ``RemoteError(R)``
  - ``Internal(I)``
  - ``StoppedTransfer(H)``
  - ``CanceledTransfer(K)``
  - ``Warning(W)``
  - ``Unknown(-)``
  - ``QueryAlreadyFinished(Q)``
  - ``QueryStillRunning(s)``
  - ``NotKnownHost(N)``,
  - ``QueryRemotelyUnknown(u)``
  - ``FileNotFound(f)``
  - ``CommandNotFound(c)``
  - ``PassThroughMode(p)``

- ``-between starttime;endtime``, ``-notbetween starttime;endtime`` permettent
  de définir des plages horaires durant lesquelles les tentatives de transferts
  peuvent ou, respectivement, ne peuvent pas être retentés. Les règles
  suivantes sont utilisées :

  - Ces arguments peuvent être utilisés plusieurs fois et peuvent être mixés ;
  - Ils ont le format suivant : ``Yn:Mn:Dn:Hn:mn:Sn`` où n
    spécifie un nombre pour chaque partie d'une date (optionnelle) comme ``Y``
    = Année, ``M`` = Mois, ``D`` = Jour, ``H`` = Heure, ``m`` = minute, ``s`` =
    seconde ;
  - Le format peut être  ``X+n``, ``X-n``, ``X=n`` ou ``Xn`` où ``X+-n``
    signifie ajouter/soustraire n à la date courante, tandis que ``X=n`` ou
    ``Xn`` signifie une valeur exacte ;
  - Si aucune spécification de temps n'est présente, ce sera la date actuelle ;
  - La date planifiée ne doit pas être dans un des intervalles définis par
    les arguments ``-notbetween`` ;
  - La date planifiée doit être dans un des intervalles définis par les
    arguments ``-between`` ;
  - Si aucun de ces arguments n'est spécifié, la date planifiée sera toujours
    valide.
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +lorsque celle-ci atteindra 0. Si elle est manquante la condition ne peut pas être appliquée.
```suggestion
  - Si ``starttime`` est plus grand que ``endtime``, ``endtime`` prendra la valeur ``starttime`` + 1 jour ;
  - Si ``starttime`` et ``endtime`` sont inférieurs à la date planifiée, ils auront également un décalage d'un jour.

- ``-count limit`` sera la limite de retentatives. La valeur limite est prise des
  ``information de transfert`` et non de la règle.

  Chaque fois que cette fonction est appelée, la valeur limite est remplacée
  par ``newlimit = limit - 1`` dans l'``information de transfert``.

  Pour assurer la cohérence, la valeur doit être dans ce champ puisque elle
  sera changée statiquement.  Cependant, une valeur doit être positionnée dans
  la règle afin de réinitialiser la valeur lorsque le décompte tombe à 0.

  Ainsi, dans la règle, ``-count resetlimit`` doit être présent, où
  ``resetlimit`` sera la nouvelle valeur lorsque celle-ci atteindra 0. Si elle
  est manquante la condition ne peut pas être appliquée.
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +normalement.
formatting
```suggestion
.. important::
  * Notez que si un précédent appel à ``RESCHEDULE`` a été réalisé et courroné
    de succès, les appels suivants seront ignorés.
  * Toutes tâches qui suivent celle-ci seront ignorées et non exécutées si la
    replanification est acceptée. Au contraire, si la replanification est
    refusée, les tâches suivantes seront exécutées normalement.
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +limite de 3 tentatives (la valeur ``retry`` sera réinitialisée à 1 en cas de 3 tentatives).
typos
```suggestion
Cet exemple illustre le cas d'une nouvelle tentative d'un transfert tombé en
erreur à cause d'une connexion impossible. La nouvelle tentative sera faite
dans une heure, si l'heure résultante n'est pas comprise 7H du matin et 7H du
soir, ni entre 1H du matin et 3H du matin avec une limite de 3 tentatives
(la valeur ``retry`` sera réinitialisée à 1 en cas de 3 tentatives).
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +-  13- ``QUIT``
formatting 
```suggestion
1. Connexion au requestHost avec le port. Si ``-ssl`` vaut ``implicit``, unt
   liaison liaison TLS native est utilisée
5. ``AUTH TLS``, ``PBSZ 0`` et ``PROT P``, si ``-ssl`` vaut ``explicit`` 
2. ``USER user``
3. ``PASS pwd``
4. ``ACCT account``, si ``-account` est renseigné
6. ``PASV``, si ``-mode`` vaut ``passive``
7. ``CWD remotepath``

   En cas d'erreur, le dossier est créé: ``MKD remotepath`` puis ``CWD
   remotepath`` (en ignorant les erreurs)

8. Si ``-pre`` est renseigné, ``extraCommand1`` avec ',' remplacés par ' '

   **note** : n'utilisez pas des commande standards FTP comme ``ACCT``,
   ``PASS``, ``REIN``, ``USER``, ``APPE``, ``STOR``, ``STOU``, ``RETR``,
   ``RMD``, ``RNFR``, ``RNTO``, ``ABOR``, ``CWD``, ``CDUP``, ``MODE``,
   ``PASV``, ``PORT``, ``STRU``, ``TYPE``, ``MDTM``, ``MLSD``, ``MLST``,
   ``SIZE``, ``AUTH``

9. ``BINARY`` (binary format)
10. Transfert des données :

    * Si ``-command`` vaut ``get``, ``RETR filepath.basename``
    * Si ``-command`` vaut ``put`, ``STOR filepath``
    * Si ``-command`` vaut ``append``, ``APPE filepath.basename``

11. Si l'argument ``-digest`` est donné et que le serveur FTP distant est
    compatible avec les commandes ``XCRC``, ``XMD5``, ``XSHA1``, ``FEAT`` (le
    résultat vérifie la présente des options disponibles) ; puis
    ``XCRC``/``XMD5``/``XSHA1`` ``filepath.basename`` ; puis localement il y
    aura la comparaison de ce hash avec le fichier local
12. Si ``-post`` est renseigné, ``extraCommand2`` avec ',' remplacés by ' '

    **note** : n'utilisez pas des commande standards FTP comme ``ACCT``, ``PASS``,
    ``REIN``, ``USER``, ``APPE``, ``STOR``, ``STOU``, ``RETR``, ``RMD``,
    ``RNFR``, ``RNTO``, ``ABOR``, ``CWD``, ``CDUP``, ``MODE``, ``PASV``,
    ``PORT``, ``STRU``, ``TYPE``, ``MDTM``, ``MLSD``, ``MLST``, ``SIZE``,
    ``AUTH``

13. ``QUIT``
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +Ceci enferra (``put``) le fichier ``/path/file`` au serveur FTP ``remotehost`` sur le port ``port`` en
typo
```suggestion
Ceci enverra (``put``) le fichier ``/path/file`` au serveur FTP ``remotehost`` sur le port ``port`` en
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +
Let's indicate when this task was introduced, and point users to a detailes
procedure!

```suggestion

.. versionadded:: 3.4.0

.. seealso::

   A fully documented to setup interactions with an ICAP server is available
   :any:`here <icap-setup>`
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +ICAP
define a reference to be used later:
```suggestion
.. _task-icap:

ICAP
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +Configuration de la tâche ICAP
add an internal reference:
```suggestion
.. _setup-icap:

Configuration de la tâche ICAP
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +suivie de ``--`` avant de poursuivre sur les options usuelles pour la commande ``TRANSFER``.
Rather than duplicating it here (documentation is a pain to maintain too ;), maybe put a note below in step 3...
```suggestion
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +------------------------------------------------------------------
typo
```suggestion
Mode opératoire préconisé pour l'installation et la configuration
-----------------------------------------------------------------
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
typo
```suggestion
Etape 1 : Permettre la connexion et l'envoi d'un fichier sain (nommé fichier)
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
typo
```suggestion
Etape 2 : Permettre la connexion et l'envoi d'un fichier malsain de test
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +
Add a note here to point to the task full documentation:
```suggestion

.. seealso::

   * Documentation de la :any:`tâche ICAP <task-icap>`
   
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/detail-tasks.rst
> +    comme OK
typo and formatting
```suggestion
* ``-file filename`` spécifie le chemin du fichier sur lequel opérer (si le nom
  est EICARTEST, un faux virus de test basé sur EICAR test sera envoyé).
* ``-to hostname`` spécifie l'adresse (via DNS ou IP) du serveur ICAP
* [``-port port``, défaut 1344]  spécifie le port à utiliser (défaut 1344)
* ``-service name`` | ``-model name``  spécifie le service ou modèle ICAP à
  utiliser
* [``-previewSize size``, défaut aucun] spécifie la taille de Preview à
  utiliser (défaut négociée)
* [``-blocSize size``, défaut 8192] spécifie la taille en émission à utiliser
  (défaut 8192)
* [``-receiveSize size``, défaut 65536] spécifie la taille en réception à
  utiliser (défaut 65536)
* [``-maxSize size``, défaut MAX_INTEGER] spécifie la taille maxmale d'un
  fichier à utiliser (défaut MAX_INTEGER)
* [``-timeout in_ms``, défaut equiv à 10 min] spécifie la limite de temps à
  utiliser (défaut equiv à 10 min)
* [``-keyPreview key -stringPreview string``, défaut aucun] spécifie la clef et
  la chaîne associée pour Options à valider (défaut aucun)
* [``-key204 key -string204 string``, défaut aucun] spécifie la clef et la
  chaîne associée pour 204 ICAP à valider (défaut aucun)
* [``-key200 key -string200 string``, défaut aucun] spécifie la clef et la
  chaîne associée pour 200 ICAP à valider (défaut aucun)
* [``-stringHttp string``, défaut aucun] spécifie la chaîne pour HTTP 200 ICAP
  à valider (défaut aucun)
* [``-logger DEBUG|INFO|WARN|ERROR``, défaut aucun] spécifie le niveau de log
  entre ``DEBUG`` | ``INFO`` | ``WARN`` | ``ERROR`` (défaut ``WARN``)
* [``-errorMove path`` | ``-errorDelete`` | ``-sendOnError``] spécifie l'action
  en cas de scan erronné : un répertoire de quarantaine, l'effacement du
  fichier, la retransmission (R66) vers un autre partenaire (mutuellement
  exclusif) (défaut aucun)
* [``-ignoreNetworkError``] spécifie que sur une erreur réseau, le fichier sera
  considéré comme OK
* [``-ignoreTooBigFileError``] spécifie que sur une erreur de fichier trop
  grand, le fichier sera considéré comme OK
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +    MAX_INTEGER)
formatting
```suggestion
* [``-previewSize size``, défaut aucun] spécifie la taille de Preview à utiliser (défaut négociée)
* [``-blocSize size``, défaut 8192] spécifie la taille en émission à utiliser (défaut 8192)
* [``-receiveSize size``, défaut 65536] spécifie la taille en réception à utiliser (défaut
   65536)
* [``-maxSize size``, défaut MAX_INTEGER] spécifie la taille Max d'un fichier à utiliser (défaut
   MAX_INTEGER)
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +         (``-stringHttp``)
formatting
```suggestion
- OPTIONS doit retourner un code ``200`` et ``Preview`` dans les balises :

  - si le Preview est indisponible, vous pouvez forcer sa taille avec l'option
    ``-previewSize`` ce qui évitera les requêtes OPTIONS pour la suite
  - si le code est ``404``, le service n'est pas connu. Il vous faut récupérer
    ce nom de service auprès de vos services informatiques (ICAP ne permet pas
    de lister les services disponibles).

- RESPMOD doit retourner :

  - un code ``204`` si le fichier est validé
  - un code ``200`` si le fichier est invalide

    - Si le fichier est sain mais qu'un code 200 est retourné, il est possible
      d'analyser les clefs/valeurs ICAP (``-key200``/``-string200``) ou le
      contenu de la partie HTTP de la réponse (``-stringHttp``)
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +    comme OK
formatting
```suggestion
* [``-errorMove path`` | ``-errorDelete`` | ``-sendOnError``] spécifie l'action
  en cas de scan erronné : un répertoire de quarantaine, l'effacement du
  fichier, la retransmission (R66) vers un autre partenaire (mutuellement
  exclusif) (défaut aucun)
* [``-ignoreNetworkError``] spécifie que sur une erreur réseau, le fichier sera
  considéré comme OK
* [``-ignoreTooBigFileError``] spécifie que sur une erreur de fichier trop
  grand, le fichier sera considéré comme OK
```

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/index.rst
> +   icap-configuration
I reckon this page would sit better in the "usage" section (which aims to be a collection os "how tos") than here in the reference of configuration files.
WDYT?

2020-06-24 16:06 UTC, bcarlin commented on doc/waarp-r66/source/configuration-details/icap-configuration.rst
> +    (défaut aucun)
formatting
```suggestion
* [``-keyPreview key -stringPreview string``, défaut aucun] spécifie la clef et la chaîne associée pour
   Options à valider (défaut aucun)
* [``-key204 key -string204 string``, défaut aucun] spécifie la clef et la chaîne associée pour 204 ICAP
   à valider (défaut aucun)
* [``-key200 key -string200 string``, défaut aucun] spécifie la clef et la chaîne associée pour 200 ICAP
   à valider (défaut aucun)
* [``-stringHttp string``, défaut aucun] spécifie la chaîne pour HTTP 200 ICAP à valider
   (défaut aucun)
```

2020-06-24 16:06 UTC, bcarlin commented on WaarpIcap/src/main/java/org/waarp/icap/IcapScanFile.java
> +  private static final String BLOC_SIZE = "blocSize";
There is a type in the argument name: it is "block" and not "bloc"...

2020-06-24 16:06 UTC, bcarlin commented on WaarpIcap/src/site/apt/index.apt
> +  * `[-blocSize size]`       Specify the Block size to use (default 8192)
should be `-blockSize`

2020-06-24 16:06 UTC, bcarlin commented on WaarpIcap/src/javadoc/overview.html
> +  <li>[-blocSize size]       Specify the Block size to use (default 8192)</li>
should be `-blockSize`

2020-06-25 07:45 UTC, fredericBregier commented on WaarpIcap/lgpl-3.0.txt
> +		   GNU LESSER GENERAL PUBLIC LICENSE
copié collé malheureux... Supprimé

2020-06-25 09:08 UTC, fredericBregier commented on doc/waarp-r66/source/configuration-details/index.rst
> +   icap-configuration
icap-configuration moved to usage section

2020-06-25 09:17 UTC, fredericBregier commented
@bcarlin changes done, please check ;-)

2020-06-25 09:20 UTC, bcarlin approved these changes
Nice catch for the "ignore too big" option!

2020-06-25 11:17 UTC, merged