Fix oodme v3
waarp/Waarp-All pull request #77
Opened 2020-08-25 15:39 UTC by fredericBregier

Under certain circumstances, Direct Memory reach a maximum of usage.
This fix tries to limit as possible this impact.
    
- File copy: no more usage of `Guava` where big block where used (512KB) and reduced direct memory (`FileChannel`)
- File reading: now using standard buffer and no more direct memory
- Hash computing: uses a byte array instead of `ByteBuf` from Netty, except when necessary
- KeepAlive algorithm fixed where under certain circumstances it failed while long task delay could lead to TimeOut erroneously
- Free quickier some buffers from Netty
- For `LocalPacket`, makes as possible unique buffer from default allocator (pooled allocation). The `DataPacket`, most often used, is optimized regarding the way of transfer (`ByteBuf` for receiving, byte array for sending).
- `NetworkPacket` was a wrapped buffer of multiple sub-buffers (from `LocalPacket`), turning it to a single Netty `ByteBuf` when reasonable.
- Direct Memory was reduced as much as possible, including Netty configuration itself (_see below_).
- One big and long IT test added to check the correctness of this (no Out Of Direct Memory Error detected)

In Netty, most of the `ByteBuf` are allocated using a Pool Allocator. Depending on usage (IO such as from network, application such as standard allocation), those could be Direct or Heap based. Netty ensures to allocate as needed and handles memory allocation in low consumption, such as Garbage collector is not called too often.
However, if the application uses intensively Direct allocation itself (not through Netty), it could lead to memory issue between Netty and the application.
This fix reduces a lot the Direct allocation out of Netty, increases the usage of Netty Pool Allocator and therefore decrease the memory pressure.

Direct Memory was reduced as much as possible.
**Default configuration is adapted at startup but could be override:**
- `-Dio.netty.noPreferDirect=true` is setup by default, it limits the usage of Direct Buffer except Netty network incoming messages
- `-Dio.netty.maxDirectMemory=0` is setup by default, Netty will use the max JDK Direct memory (recommended).
    
_**Recommended value for `io.netty.maxDirectMemory` is 0**_. Giving too small value (>0) coud cause issues.
- Value of -1 is default behavior of Netty and is also a good option for R66 (Netty uses twice Direct memory maximum from JDK without Cleaner).
- Value of 0 lets Netty allocate within Direct Memory, using JDK max.
- Value of greater than 0 should not be used (could limit too much memory allocation for Netty) and **is really not recommended**.    
  
Note however that Direct memory is still used by Netty itself for incoming messages. Disallowing totally Direct buffer could leads to serious issues on memory usage (GC overacting). Therefore, extra arguments such as `-Dio.netty.noUnsafe=true` **is intensively not recommended**.

As previously, one could also limit usage of Direct Memory by specifying in XML configuration file in `limit` section the value `usenio` to `False`.

2020-08-26 15:47 UTC, bcarlin requested changes
That's a lot of optimizations.
I did not spot any obvious errors... just a few output that I think should be in the logs (I think they already are in netty initialization logs...): it is always unsettling to have output starting with "ERROR" when the server starts ok.

Other than that, in my test, it fixed the OODM errors I had before and stabilized the RAM usage.
good job !

2020-08-26 15:47 UTC, bcarlin commented on WaarpCommon/src/main/java/org/waarp/common/utility/SystemPropertyUtil.java
> +                                            .get(IO_NETTY_NOPREFERDIRECT));
id.

2020-08-26 15:47 UTC, bcarlin commented on WaarpCommon/src/main/java/org/waarp/common/utility/SystemPropertyUtil.java
> +                                            .get(IO_NETTY_ALLOCATOR_TYPE));
This is for debugging. It belongs more to the log file than to the error output...

2020-08-26 15:47 UTC, bcarlin commented on WaarpCommon/src/main/java/org/waarp/common/utility/SystemPropertyUtil.java
> +                                            .get(IO_NETTY_MAXDIRECTMEMORY));
id.

2020-08-26 18:24 UTC, fredericBregier commented on WaarpCommon/src/main/java/org/waarp/common/utility/SystemPropertyUtil.java
> +                                            .get(IO_NETTY_NOPREFERDIRECT));
Agree

2020-09-01 15:52 UTC, fredericBregier commented
@bcarlin All done and checked

2020-09-04 10:03 UTC, bcarlin commented
I guess this PR can be closed, as it is included in #82 ?

2020-09-04 12:55 UTC, merged